# Generated by Django 6.0.6 on 2026-07-07 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_type', models.CharField(choices=[('COMPLAINT', 'Complaint'), ('LEAVE', 'Leave Application')], max_length=20)),
                ('resolve_status', models.CharField(choices=[('RAISED', 'Raised'), ('PROCESSING', 'Processing'), ('CLOSED', 'Closed')], default='RAISED', max_length=20)),
                ('detailed_issue', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_tickets', to='accounts.employeeinfo')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_tickets', to='accounts.employeeinfo')),
            ],
        ),
    ]
