# Generated by Django 6.0.6 on 2026-07-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='General', max_length=200),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('COMPLAINT', 'Complaint'), ('LEAVE', 'Leave Application')], default='COMPLAINT', max_length=20),
        ),
    ]
