# Generated by Django 6.0.6 on 2026-07-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_title_alter_ticket_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
